// Mocks generated by Mockito 5.4.5 from annotations
// in newton_tech_interview_quiz/test/domain/usecases/get_spacex_launches_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:newton_tech_interview_quiz/data/remote_data_sources/remote_v3_data_source.dart'
    as _i2;
import 'package:newton_tech_interview_quiz/data/repositories/spacex_repository_impl.dart'
    as _i3;
import 'package:newton_tech_interview_quiz/domain/value_objects/spacex_flight.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteV3DataSource_0 extends _i1.SmartFake
    implements _i2.RemoteV3DataSource {
  _FakeRemoteV3DataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpaceXRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpaceXRepositoryImpl extends _i1.Mock
    implements _i3.SpaceXRepositoryImpl {
  MockSpaceXRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RemoteV3DataSource get remoteV3DataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteV3DataSource),
            returnValue: _FakeRemoteV3DataSource_0(
              this,
              Invocation.getter(#remoteV3DataSource),
            ),
          )
          as _i2.RemoteV3DataSource);

  @override
  _i4.Future<List<_i5.SpaceXFlight>> getLaunches() =>
      (super.noSuchMethod(
            Invocation.method(#getLaunches, []),
            returnValue: _i4.Future<List<_i5.SpaceXFlight>>.value(
              <_i5.SpaceXFlight>[],
            ),
          )
          as _i4.Future<List<_i5.SpaceXFlight>>);
}
